# TCL File Generated by Component Editor 15.0
# Sun Aug 28 03:00:40 CST 2016
# DO NOT MODIFY


# 
# bit_unpacker "Bit Unpacker" v1.0
#  2016.08.28.03:00:40
# 
# 

# 
# request TCL package from ACDS 15.0
# 
package require -exact qsys 15.0


# 
# module bit_unpacker
# 
set_module_property DESCRIPTION ""
set_module_property NAME bit_unpacker
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "Bit Unpacker"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL bit_unpacker
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file bit_unpacker.vhd VHDL PATH src/vga_st/bit_unpacker.vhd TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL bit_unpacker
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file bit_unpacker.vhd VHDL PATH src/vga_st/bit_unpacker.vhd

add_fileset SIM_VHDL SIM_VHDL "" ""
set_fileset_property SIM_VHDL TOP_LEVEL bit_unpacker
set_fileset_property SIM_VHDL ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VHDL ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file bit_unpacker.vhd VHDL PATH src/vga_st/bit_unpacker.vhd


# 
# parameters
# 
add_parameter DIN_WIDTH POSITIVE 8
set_parameter_property DIN_WIDTH DEFAULT_VALUE 8
set_parameter_property DIN_WIDTH DISPLAY_NAME DIN_WIDTH
set_parameter_property DIN_WIDTH TYPE POSITIVE
set_parameter_property DIN_WIDTH UNITS None
set_parameter_property DIN_WIDTH ALLOWED_RANGES 1:2147483647
set_parameter_property DIN_WIDTH HDL_PARAMETER true
add_parameter DOUT_WIDTH POSITIVE 4
set_parameter_property DOUT_WIDTH DEFAULT_VALUE 4
set_parameter_property DOUT_WIDTH DISPLAY_NAME DOUT_WIDTH
set_parameter_property DOUT_WIDTH TYPE POSITIVE
set_parameter_property DOUT_WIDTH UNITS None
set_parameter_property DOUT_WIDTH ALLOWED_RANGES 1:2147483647
set_parameter_property DOUT_WIDTH HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point sink
# 
add_interface sink avalon_streaming end
set_interface_property sink associatedClock clock
set_interface_property sink associatedReset reset
set_interface_property sink dataBitsPerSymbol 8
set_interface_property sink errorDescriptor ""
set_interface_property sink firstSymbolInHighOrderBits true
set_interface_property sink maxChannel 0
set_interface_property sink readyLatency 0
set_interface_property sink ENABLED true
set_interface_property sink EXPORT_OF ""
set_interface_property sink PORT_NAME_MAP ""
set_interface_property sink CMSIS_SVD_VARIABLES ""
set_interface_property sink SVD_ADDRESS_GROUP ""

add_interface_port sink din_data data Input din_width
add_interface_port sink din_ready ready Output 1


# 
# connection point source
# 
add_interface source avalon_streaming start
set_interface_property source associatedClock clock
set_interface_property source associatedReset reset
set_interface_property source dataBitsPerSymbol 1
set_interface_property source errorDescriptor ""
set_interface_property source firstSymbolInHighOrderBits true
set_interface_property source maxChannel 0
set_interface_property source readyLatency 0
set_interface_property source ENABLED true
set_interface_property source EXPORT_OF ""
set_interface_property source PORT_NAME_MAP ""
set_interface_property source CMSIS_SVD_VARIABLES ""
set_interface_property source SVD_ADDRESS_GROUP ""

add_interface_port source dout_ready ready Input 1
add_interface_port source dout_data data Output dout_width

