# TCL File Generated by Component Editor 15.0
# Tue Aug 23 22:02:19 CST 2016
# DO NOT MODIFY


# 
# bitpacker "Bit Packer" v1.1
#  2016.08.23.22:02:19
# 
# 

# 
# request TCL package from ACDS 15.0
# 
package require -exact qsys 15.0


# 
# module bitpacker
# 
set_module_property DESCRIPTION ""
set_module_property NAME bitpacker
set_module_property VERSION 1.1
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "Bit Packer"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL bitpacker
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file bitpacker.vhd VHDL PATH src/hsv/bitpacker.vhd TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL bitpacker
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file bitpacker.vhd VHDL PATH src/hsv/bitpacker.vhd

add_fileset SIM_VHDL SIM_VHDL "" ""
set_fileset_property SIM_VHDL TOP_LEVEL bitpacker
set_fileset_property SIM_VHDL ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VHDL ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file bitpacker.vhd VHDL PATH src/hsv/bitpacker.vhd


# 
# parameters
# 
add_parameter PACK_LENGTH POSITIVE 8
set_parameter_property PACK_LENGTH DEFAULT_VALUE 8
set_parameter_property PACK_LENGTH DISPLAY_NAME PACK_LENGTH
set_parameter_property PACK_LENGTH TYPE POSITIVE
set_parameter_property PACK_LENGTH UNITS None
set_parameter_property PACK_LENGTH ALLOWED_RANGES 1:2147483647
set_parameter_property PACK_LENGTH HDL_PARAMETER true
add_parameter FIRST_SYMBOL_IN_MSB NATURAL 0
set_parameter_property FIRST_SYMBOL_IN_MSB DEFAULT_VALUE 0
set_parameter_property FIRST_SYMBOL_IN_MSB DISPLAY_NAME FIRST_SYMBOL_IN_MSB
set_parameter_property FIRST_SYMBOL_IN_MSB TYPE NATURAL
set_parameter_property FIRST_SYMBOL_IN_MSB UNITS None
set_parameter_property FIRST_SYMBOL_IN_MSB HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point din
# 
add_interface din avalon_streaming end
set_interface_property din associatedClock clock
set_interface_property din associatedReset reset
set_interface_property din dataBitsPerSymbol 1
set_interface_property din errorDescriptor ""
set_interface_property din firstSymbolInHighOrderBits true
set_interface_property din maxChannel 0
set_interface_property din readyLatency 0
set_interface_property din ENABLED true
set_interface_property din EXPORT_OF ""
set_interface_property din PORT_NAME_MAP ""
set_interface_property din CMSIS_SVD_VARIABLES ""
set_interface_property din SVD_ADDRESS_GROUP ""

add_interface_port din din_valid valid Input 1
add_interface_port din din_data data Input 1
add_interface_port din din_sop startofpacket Input 1
add_interface_port din din_eop endofpacket Input 1


# 
# connection point dout
# 
add_interface dout avalon_streaming start
set_interface_property dout associatedClock clock
set_interface_property dout associatedReset reset
set_interface_property dout dataBitsPerSymbol 8
set_interface_property dout errorDescriptor ""
set_interface_property dout firstSymbolInHighOrderBits true
set_interface_property dout maxChannel 0
set_interface_property dout readyLatency 0
set_interface_property dout ENABLED true
set_interface_property dout EXPORT_OF ""
set_interface_property dout PORT_NAME_MAP ""
set_interface_property dout CMSIS_SVD_VARIABLES ""
set_interface_property dout SVD_ADDRESS_GROUP ""

add_interface_port dout dout_data data Output pack_length
add_interface_port dout dout_eop endofpacket Output 1
add_interface_port dout dout_sop startofpacket Output 1
add_interface_port dout dout_valid valid Output 1

