# TCL File Generated by Component Editor 15.0
# Sat Aug 13 16:06:17 GMT+08:00 2016
# DO NOT MODIFY


# 
# camera_seq "Camera Sequential" v1.0
#  2016.08.13.16:06:17
# 
# 

# 
# request TCL package from ACDS 15.0
# 
package require -exact qsys 15.0


# 
# module camera_seq
# 
set_module_property DESCRIPTION ""
set_module_property NAME camera_seq
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "Camera Sequential"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL camera_controller_seq
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file NEEE.vhd VHDL PATH src/NEEE.vhd
add_fileset_file camera_seq.vhd VHDL PATH src/camera_seq.vhd
add_fileset_file ip_fifo.vhd VHDL PATH src/ip_fifo.vhd
add_fileset_file st_write_buffer.vhd VHDL PATH src/st_write_buffer.vhd
add_fileset_file camera_controller_seq.vhd VHDL PATH src/camera_controller_seq.vhd TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL camera_controller_seq
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file NEEE.vhd VHDL PATH src/NEEE.vhd
add_fileset_file camera_seq.vhd VHDL PATH src/camera_seq.vhd
add_fileset_file ip_fifo.vhd VHDL PATH src/ip_fifo.vhd
add_fileset_file st_write_buffer.vhd VHDL PATH src/st_write_buffer.vhd
add_fileset_file camera_controller_seq.vhd VHDL PATH src/camera_controller_seq.vhd

add_fileset SIM_VHDL SIM_VHDL "" ""
set_fileset_property SIM_VHDL TOP_LEVEL camera_controller_seq
set_fileset_property SIM_VHDL ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VHDL ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file NEEE.vhd VHDL PATH src/NEEE.vhd
add_fileset_file camera_seq.vhd VHDL PATH src/camera_seq.vhd
add_fileset_file ip_fifo.vhd VHDL PATH src/ip_fifo.vhd
add_fileset_file st_write_buffer.vhd VHDL PATH src/st_write_buffer.vhd
add_fileset_file camera_controller_seq.vhd VHDL PATH src/camera_controller_seq.vhd


# 
# parameters
# 
add_parameter DATA_WIDTH POSITIVE 8
set_parameter_property DATA_WIDTH DEFAULT_VALUE 8
set_parameter_property DATA_WIDTH DISPLAY_NAME DATA_WIDTH
set_parameter_property DATA_WIDTH TYPE POSITIVE
set_parameter_property DATA_WIDTH UNITS None
set_parameter_property DATA_WIDTH ALLOWED_RANGES 1:2147483647
set_parameter_property DATA_WIDTH HDL_PARAMETER true
add_parameter FIFO_LENGTH_LOG_2 POSITIVE 8
set_parameter_property FIFO_LENGTH_LOG_2 DEFAULT_VALUE 8
set_parameter_property FIFO_LENGTH_LOG_2 DISPLAY_NAME FIFO_LENGTH_LOG_2
set_parameter_property FIFO_LENGTH_LOG_2 TYPE POSITIVE
set_parameter_property FIFO_LENGTH_LOG_2 UNITS None
set_parameter_property FIFO_LENGTH_LOG_2 ALLOWED_RANGES 1:2147483647
set_parameter_property FIFO_LENGTH_LOG_2 HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point aso_out
# 
add_interface aso_out avalon_streaming start
set_interface_property aso_out associatedClock clock
set_interface_property aso_out associatedReset reset
set_interface_property aso_out dataBitsPerSymbol 8
set_interface_property aso_out errorDescriptor ""
set_interface_property aso_out firstSymbolInHighOrderBits true
set_interface_property aso_out maxChannel 0
set_interface_property aso_out readyLatency 1
set_interface_property aso_out ENABLED true
set_interface_property aso_out EXPORT_OF ""
set_interface_property aso_out PORT_NAME_MAP ""
set_interface_property aso_out CMSIS_SVD_VARIABLES ""
set_interface_property aso_out SVD_ADDRESS_GROUP ""

add_interface_port aso_out data data Output data_width
add_interface_port aso_out ready ready Input 1
add_interface_port aso_out valid valid Output 1
add_interface_port aso_out eop endofpacket Output 1
add_interface_port aso_out sop startofpacket Output 1


# 
# connection point conduit
# 
add_interface conduit conduit end
set_interface_property conduit associatedClock clock
set_interface_property conduit associatedReset ""
set_interface_property conduit ENABLED true
set_interface_property conduit EXPORT_OF ""
set_interface_property conduit PORT_NAME_MAP ""
set_interface_property conduit CMSIS_SVD_VARIABLES ""
set_interface_property conduit SVD_ADDRESS_GROUP ""

add_interface_port conduit clk_camera clk_camera Input 1
add_interface_port conduit enable_n enable_n Input 1
add_interface_port conduit CAM_DIN cam_din Input 8
add_interface_port conduit CAM_HREF cam_href Input 1
add_interface_port conduit CAM_PCLK cam_pclk Input 1
add_interface_port conduit CAM_PWDN cam_pwdn Output 1
add_interface_port conduit CAM_RESET cam_reset Output 1
add_interface_port conduit CAM_VSYNC cam_vsync Input 1
add_interface_port conduit CAM_XCLK cam_xclk Output 1

