# TCL File Generated by Component Editor 15.0
# Fri Aug 19 20:54:59 CST 2016
# DO NOT MODIFY


# 
# camera_st "Camera ST" v1.0
#  2016.08.19.20:54:59
# 
# 

# 
# request TCL package from ACDS 15.0
# 
package require -exact qsys 15.0


# 
# module camera_st
# 
set_module_property DESCRIPTION ""
set_module_property NAME camera_st
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "Camera ST"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL camera
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file NEEE.vhd VHDL PATH src/NEEE.vhd
add_fileset_file ip_fifo.vhd VHDL PATH src/ip_fifo.vhd
add_fileset_file camera.vhd VHDL PATH src/camera_st/camera.vhd TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL camera
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file NEEE.vhd VHDL PATH src/NEEE.vhd
add_fileset_file ip_fifo.vhd VHDL PATH src/ip_fifo.vhd
add_fileset_file camera.vhd VHDL PATH src/camera_st/camera.vhd

add_fileset SIM_VHDL SIM_VHDL "" ""
set_fileset_property SIM_VHDL TOP_LEVEL camera
set_fileset_property SIM_VHDL ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VHDL ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file NEEE.vhd VHDL PATH src/NEEE.vhd
add_fileset_file ip_fifo.vhd VHDL PATH src/ip_fifo.vhd
add_fileset_file camera.vhd VHDL PATH src/camera_st/camera.vhd


# 
# parameters
# 
add_parameter DATA_WIDTH POSITIVE 24
set_parameter_property DATA_WIDTH DEFAULT_VALUE 24
set_parameter_property DATA_WIDTH DISPLAY_NAME DATA_WIDTH
set_parameter_property DATA_WIDTH TYPE POSITIVE
set_parameter_property DATA_WIDTH UNITS None
set_parameter_property DATA_WIDTH ALLOWED_RANGES 1:2147483647
set_parameter_property DATA_WIDTH HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock start
set_interface_property clock associatedDirectClock ""
set_interface_property clock clockRate 0
set_interface_property clock clockRateKnown false
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Output 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock ""
set_interface_property reset synchronousEdges NONE
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point conduit
# 
add_interface conduit conduit end
set_interface_property conduit associatedClock ""
set_interface_property conduit associatedReset ""
set_interface_property conduit ENABLED true
set_interface_property conduit EXPORT_OF ""
set_interface_property conduit PORT_NAME_MAP ""
set_interface_property conduit CMSIS_SVD_VARIABLES ""
set_interface_property conduit SVD_ADDRESS_GROUP ""

add_interface_port conduit CAM_DIN cam_din Input 8
add_interface_port conduit CAM_HREF cam_href Input 1
add_interface_port conduit CAM_PCLK cam_pclk Input 1
add_interface_port conduit CAM_PWDN cam_pwdn Output 1
add_interface_port conduit CAM_RESET cam_reset Output 1
add_interface_port conduit CAM_VSYNC cam_vsync Input 1
add_interface_port conduit CAM_XCLK cam_xclk Output 1
add_interface_port conduit clk_camera clk_camera Input 1
add_interface_port conduit enable_n enable_n Input 1


# 
# connection point st0
# 
add_interface st0 avalon_streaming start
set_interface_property st0 associatedClock clock
set_interface_property st0 associatedReset reset
set_interface_property st0 dataBitsPerSymbol 8
set_interface_property st0 errorDescriptor ""
set_interface_property st0 firstSymbolInHighOrderBits true
set_interface_property st0 maxChannel 0
set_interface_property st0 readyLatency 0
set_interface_property st0 ENABLED true
set_interface_property st0 EXPORT_OF ""
set_interface_property st0 PORT_NAME_MAP ""
set_interface_property st0 CMSIS_SVD_VARIABLES ""
set_interface_property st0 SVD_ADDRESS_GROUP ""

add_interface_port st0 valid valid Output 1
add_interface_port st0 sop startofpacket Output 1
add_interface_port st0 eop endofpacket Output 1
add_interface_port st0 data data Output data_width

