# TCL File Generated by Component Editor 15.0
# Sat Aug 27 20:53:03 CST 2016
# DO NOT MODIFY


# 
# dummy_buffer_switcher "Dummy Buffer Switcher" v1.0
#  2016.08.27.20:53:03
# 
# 

# 
# request TCL package from ACDS 15.0
# 
package require -exact qsys 15.0


# 
# module dummy_buffer_switcher
# 
set_module_property DESCRIPTION ""
set_module_property NAME dummy_buffer_switcher
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "Dummy Buffer Switcher"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL dummy_buffer_switcher
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file dummy_buffer_switcher.vhd VHDL PATH src/util/dummy_buffer_switcher.vhd TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL dummy_buffer_switcher
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file dummy_buffer_switcher.vhd VHDL PATH src/util/dummy_buffer_switcher.vhd

add_fileset SIM_VHDL SIM_VHDL "" ""
set_fileset_property SIM_VHDL TOP_LEVEL dummy_buffer_switcher
set_fileset_property SIM_VHDL ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VHDL ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file dummy_buffer_switcher.vhd VHDL PATH src/util/dummy_buffer_switcher.vhd


# 
# parameters
# 
add_parameter FIXED_BUFFER_PORT STD_LOGIC_VECTOR 0
set_parameter_property FIXED_BUFFER_PORT DEFAULT_VALUE 0
set_parameter_property FIXED_BUFFER_PORT DISPLAY_NAME FIXED_BUFFER_PORT
set_parameter_property FIXED_BUFFER_PORT TYPE STD_LOGIC_VECTOR
set_parameter_property FIXED_BUFFER_PORT UNITS None
set_parameter_property FIXED_BUFFER_PORT ALLOWED_RANGES 0:3
set_parameter_property FIXED_BUFFER_PORT HDL_PARAMETER true


# 
# display items
# 


# 
# connection point buffer_switcher
# 
add_interface buffer_switcher conduit end
set_interface_property buffer_switcher associatedClock clock
set_interface_property buffer_switcher associatedReset ""
set_interface_property buffer_switcher ENABLED true
set_interface_property buffer_switcher EXPORT_OF ""
set_interface_property buffer_switcher PORT_NAME_MAP ""
set_interface_property buffer_switcher CMSIS_SVD_VARIABLES ""
set_interface_property buffer_switcher SVD_ADDRESS_GROUP ""

add_interface_port buffer_switcher buffer_vsync buffer_vsync Input 1
add_interface_port buffer_switcher buffer_port buffer_port Output 2


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1

