# TCL File Generated by Component Editor 15.0
# Fri Aug 12 17:10:04 GMT+08:00 2016
# DO NOT MODIFY


# 
# frame_buffer_switcher "Frame Buffer Switcher" v1.0
#  2016.08.12.17:10:04
# 
# 

# 
# request TCL package from ACDS 15.0
# 
package require -exact qsys 15.0


# 
# module frame_buffer_switcher
# 
set_module_property DESCRIPTION ""
set_module_property NAME frame_buffer_switcher
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "Frame Buffer Switcher"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL frame_buffer
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file NEEE.vhd VHDL PATH src/NEEE.vhd
add_fileset_file frame_buffer.vhd VHDL PATH src/frame_buffer.vhd TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL frame_buffer
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file NEEE.vhd VHDL PATH src/NEEE.vhd
add_fileset_file frame_buffer.vhd VHDL PATH src/frame_buffer.vhd

add_fileset SIM_VHDL SIM_VHDL "" ""
set_fileset_property SIM_VHDL TOP_LEVEL frame_buffer
set_fileset_property SIM_VHDL ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VHDL ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file NEEE.vhd VHDL PATH src/NEEE.vhd
add_fileset_file frame_buffer.vhd VHDL PATH src/frame_buffer.vhd


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point read_vsync
# 
add_interface read_vsync conduit end
set_interface_property read_vsync associatedClock clock
set_interface_property read_vsync associatedReset ""
set_interface_property read_vsync ENABLED true
set_interface_property read_vsync EXPORT_OF ""
set_interface_property read_vsync PORT_NAME_MAP ""
set_interface_property read_vsync CMSIS_SVD_VARIABLES ""
set_interface_property read_vsync SVD_ADDRESS_GROUP ""

add_interface_port read_vsync read_vsync vsync Input 1


# 
# connection point write_vsync
# 
add_interface write_vsync conduit end
set_interface_property write_vsync associatedClock clock
set_interface_property write_vsync associatedReset ""
set_interface_property write_vsync ENABLED true
set_interface_property write_vsync EXPORT_OF ""
set_interface_property write_vsync PORT_NAME_MAP ""
set_interface_property write_vsync CMSIS_SVD_VARIABLES ""
set_interface_property write_vsync SVD_ADDRESS_GROUP ""

add_interface_port write_vsync write_vsync vsync Input 1


# 
# connection point read_buffer
# 
add_interface read_buffer conduit end
set_interface_property read_buffer associatedClock clock
set_interface_property read_buffer associatedReset ""
set_interface_property read_buffer ENABLED true
set_interface_property read_buffer EXPORT_OF ""
set_interface_property read_buffer PORT_NAME_MAP ""
set_interface_property read_buffer CMSIS_SVD_VARIABLES ""
set_interface_property read_buffer SVD_ADDRESS_GROUP ""

add_interface_port read_buffer read_buffer address Output 2


# 
# connection point write_buffer
# 
add_interface write_buffer conduit end
set_interface_property write_buffer associatedClock clock
set_interface_property write_buffer associatedReset ""
set_interface_property write_buffer ENABLED true
set_interface_property write_buffer EXPORT_OF ""
set_interface_property write_buffer PORT_NAME_MAP ""
set_interface_property write_buffer CMSIS_SVD_VARIABLES ""
set_interface_property write_buffer SVD_ADDRESS_GROUP ""

add_interface_port write_buffer write_buffer address Output 2


# 
# connection point enable
# 
add_interface enable conduit end
set_interface_property enable associatedClock clock
set_interface_property enable associatedReset ""
set_interface_property enable ENABLED true
set_interface_property enable EXPORT_OF ""
set_interface_property enable PORT_NAME_MAP ""
set_interface_property enable CMSIS_SVD_VARIABLES ""
set_interface_property enable SVD_ADDRESS_GROUP ""

add_interface_port enable enable enable Input 1

