# TCL File Generated by Component Editor 15.0
# Thu Aug 25 05:43:48 CST 2016
# DO NOT MODIFY


# 
# frame_buffer_switcher "Dual-Clock Frame Buffer Switcher" v2.0
#  2016.08.25.05:43:48
# Dual-Clock Frame Buffer Switcher
# 

# 
# request TCL package from ACDS 15.0
# 
package require -exact qsys 15.0


# 
# module frame_buffer_switcher
# 
set_module_property DESCRIPTION "Dual-Clock Frame Buffer Switcher"
set_module_property NAME frame_buffer_switcher
set_module_property VERSION 2.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "Dual-Clock Frame Buffer Switcher"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL frame_buffer
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file frame_buffer.vhd VHDL PATH src/frame_buffer.vhd TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL frame_buffer
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file frame_buffer.vhd VHDL PATH src/frame_buffer.vhd

add_fileset SIM_VHDL SIM_VHDL "" ""
set_fileset_property SIM_VHDL TOP_LEVEL frame_buffer
set_fileset_property SIM_VHDL ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VHDL ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file frame_buffer.vhd VHDL PATH src/frame_buffer.vhd


# 
# parameters
# 


# 
# display items
# 


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock ""
set_interface_property reset synchronousEdges NONE
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point read_buffer
# 
add_interface read_buffer conduit end
set_interface_property read_buffer associatedClock read_clock
set_interface_property read_buffer associatedReset ""
set_interface_property read_buffer ENABLED true
set_interface_property read_buffer EXPORT_OF ""
set_interface_property read_buffer PORT_NAME_MAP ""
set_interface_property read_buffer CMSIS_SVD_VARIABLES ""
set_interface_property read_buffer SVD_ADDRESS_GROUP ""

add_interface_port read_buffer read_buffer buffer_port Output 2
add_interface_port read_buffer read_vsync buffer_vsync Input 1


# 
# connection point write_buffer
# 
add_interface write_buffer conduit end
set_interface_property write_buffer associatedClock write_clk
set_interface_property write_buffer associatedReset ""
set_interface_property write_buffer ENABLED true
set_interface_property write_buffer EXPORT_OF ""
set_interface_property write_buffer PORT_NAME_MAP ""
set_interface_property write_buffer CMSIS_SVD_VARIABLES ""
set_interface_property write_buffer SVD_ADDRESS_GROUP ""

add_interface_port write_buffer write_buffer buffer_port Output 2
add_interface_port write_buffer write_vsync buffer_vsync Input 1


# 
# connection point enable
# 
add_interface enable conduit end
set_interface_property enable associatedClock ""
set_interface_property enable associatedReset ""
set_interface_property enable ENABLED true
set_interface_property enable EXPORT_OF ""
set_interface_property enable PORT_NAME_MAP ""
set_interface_property enable CMSIS_SVD_VARIABLES ""
set_interface_property enable SVD_ADDRESS_GROUP ""

add_interface_port enable enable enable Input 1


# 
# connection point write_clk
# 
add_interface write_clk clock end
set_interface_property write_clk clockRate 0
set_interface_property write_clk ENABLED true
set_interface_property write_clk EXPORT_OF ""
set_interface_property write_clk PORT_NAME_MAP ""
set_interface_property write_clk CMSIS_SVD_VARIABLES ""
set_interface_property write_clk SVD_ADDRESS_GROUP ""

add_interface_port write_clk write_clk clk Input 1


# 
# connection point read_clock
# 
add_interface read_clock clock end
set_interface_property read_clock clockRate 0
set_interface_property read_clock ENABLED true
set_interface_property read_clock EXPORT_OF ""
set_interface_property read_clock PORT_NAME_MAP ""
set_interface_property read_clock CMSIS_SVD_VARIABLES ""
set_interface_property read_clock SVD_ADDRESS_GROUP ""

add_interface_port read_clock read_clk clk Input 1

