# TCL File Generated by Component Editor 15.0
# Sat Aug 27 23:57:40 GMT+08:00 2016
# DO NOT MODIFY


# 
# overlay_decoder "Overlay Decoder" v1.0
#  2016.08.27.23:57:40
# 
# 

# 
# request TCL package from ACDS 15.0
# 
package require -exact qsys 15.0


# 
# module overlay_decoder
# 
set_module_property DESCRIPTION ""
set_module_property NAME overlay_decoder
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "Overlay Decoder"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL overlay_decoder
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file overlay_decoder.vhd VHDL PATH src/vga_st/overlay_decoder.vhd TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL overlay_decoder
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file overlay_decoder.vhd VHDL PATH src/vga_st/overlay_decoder.vhd

add_fileset SIM_VHDL SIM_VHDL "" ""
set_fileset_property SIM_VHDL TOP_LEVEL overlay_decoder
set_fileset_property SIM_VHDL ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VHDL ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file overlay_decoder.vhd VHDL PATH src/vga_st/overlay_decoder.vhd


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point st_out
# 
add_interface st_out avalon_streaming start
set_interface_property st_out associatedClock clock
set_interface_property st_out dataBitsPerSymbol 8
set_interface_property st_out errorDescriptor ""
set_interface_property st_out firstSymbolInHighOrderBits true
set_interface_property st_out maxChannel 0
set_interface_property st_out readyLatency 0
set_interface_property st_out ENABLED true
set_interface_property st_out EXPORT_OF ""
set_interface_property st_out PORT_NAME_MAP ""
set_interface_property st_out CMSIS_SVD_VARIABLES ""
set_interface_property st_out SVD_ADDRESS_GROUP ""

add_interface_port st_out out_data data Output 32
add_interface_port st_out out_ready ready Input 1


# 
# connection point st_in
# 
add_interface st_in avalon_streaming end
set_interface_property st_in associatedClock clock
set_interface_property st_in dataBitsPerSymbol 4
set_interface_property st_in errorDescriptor ""
set_interface_property st_in firstSymbolInHighOrderBits true
set_interface_property st_in maxChannel 0
set_interface_property st_in readyLatency 0
set_interface_property st_in ENABLED true
set_interface_property st_in EXPORT_OF ""
set_interface_property st_in PORT_NAME_MAP ""
set_interface_property st_in CMSIS_SVD_VARIABLES ""
set_interface_property st_in SVD_ADDRESS_GROUP ""

add_interface_port st_in in_ready ready Output 1
add_interface_port st_in in_data data Input 4

