# TCL File Generated by Component Editor 15.0
# Wed Oct 12 21:42:58 CST 2016
# DO NOT MODIFY


# 
# st_naive_mux "Naive-ST Mux" v1.0
#  2016.10.12.21:42:58
# 
# 

# 
# request TCL package from ACDS 15.0
# 
package require -exact qsys 15.0


# 
# module st_naive_mux
# 
set_module_property DESCRIPTION ""
set_module_property NAME st_naive_mux
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "Naive-ST Mux"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL st_naive_mux
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file st_naive_mux.vhd VHDL PATH src/util/st_naive_mux.vhd TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL st_naive_mux
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file st_naive_mux.vhd VHDL PATH src/util/st_naive_mux.vhd

add_fileset SIM_VHDL SIM_VHDL "" ""
set_fileset_property SIM_VHDL TOP_LEVEL st_naive_mux
set_fileset_property SIM_VHDL ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VHDL ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file st_naive_mux.vhd VHDL PATH src/util/st_naive_mux.vhd


# 
# parameters
# 
add_parameter DATA_WIDTH POSITIVE 32
set_parameter_property DATA_WIDTH DEFAULT_VALUE 32
set_parameter_property DATA_WIDTH DISPLAY_NAME DATA_WIDTH
set_parameter_property DATA_WIDTH TYPE POSITIVE
set_parameter_property DATA_WIDTH UNITS None
set_parameter_property DATA_WIDTH ALLOWED_RANGES 1:2147483647
set_parameter_property DATA_WIDTH HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point din0
# 
add_interface din0 avalon_streaming end
set_interface_property din0 associatedClock clock
set_interface_property din0 associatedReset reset
set_interface_property din0 dataBitsPerSymbol 8
set_interface_property din0 errorDescriptor ""
set_interface_property din0 firstSymbolInHighOrderBits true
set_interface_property din0 maxChannel 0
set_interface_property din0 readyLatency 0
set_interface_property din0 ENABLED true
set_interface_property din0 EXPORT_OF ""
set_interface_property din0 PORT_NAME_MAP ""
set_interface_property din0 CMSIS_SVD_VARIABLES ""
set_interface_property din0 SVD_ADDRESS_GROUP ""

add_interface_port din0 asi_din0_data data Input data_width
add_interface_port din0 asi_din0_startofpacket startofpacket Input 1
add_interface_port din0 asi_din0_endofpacket endofpacket Input 1
add_interface_port din0 asi_din0_valid valid Input 1


# 
# connection point din1
# 
add_interface din1 avalon_streaming end
set_interface_property din1 associatedClock clock
set_interface_property din1 associatedReset reset
set_interface_property din1 dataBitsPerSymbol 8
set_interface_property din1 errorDescriptor ""
set_interface_property din1 firstSymbolInHighOrderBits true
set_interface_property din1 maxChannel 0
set_interface_property din1 readyLatency 0
set_interface_property din1 ENABLED true
set_interface_property din1 EXPORT_OF ""
set_interface_property din1 PORT_NAME_MAP ""
set_interface_property din1 CMSIS_SVD_VARIABLES ""
set_interface_property din1 SVD_ADDRESS_GROUP ""

add_interface_port din1 asi_din1_data data Input data_width
add_interface_port din1 asi_din1_startofpacket startofpacket Input 1
add_interface_port din1 asi_din1_endofpacket endofpacket Input 1
add_interface_port din1 asi_din1_valid valid Input 1


# 
# connection point dout
# 
add_interface dout avalon_streaming start
set_interface_property dout associatedClock clock
set_interface_property dout associatedReset reset
set_interface_property dout dataBitsPerSymbol 8
set_interface_property dout errorDescriptor ""
set_interface_property dout firstSymbolInHighOrderBits true
set_interface_property dout maxChannel 0
set_interface_property dout readyLatency 0
set_interface_property dout ENABLED true
set_interface_property dout EXPORT_OF ""
set_interface_property dout PORT_NAME_MAP ""
set_interface_property dout CMSIS_SVD_VARIABLES ""
set_interface_property dout SVD_ADDRESS_GROUP ""

add_interface_port dout aso_dout_data data Output data_width
add_interface_port dout aso_dout_startofpacket startofpacket Output 1
add_interface_port dout aso_dout_endofpacket endofpacket Output 1
add_interface_port dout aso_dout_valid valid Output 1


# 
# connection point conduit
# 
add_interface conduit conduit end
set_interface_property conduit associatedClock clock
set_interface_property conduit associatedReset ""
set_interface_property conduit ENABLED true
set_interface_property conduit EXPORT_OF ""
set_interface_property conduit PORT_NAME_MAP ""
set_interface_property conduit CMSIS_SVD_VARIABLES ""
set_interface_property conduit SVD_ADDRESS_GROUP ""

add_interface_port conduit coe_conduit_sel export Input 1

