# TCL File Generated by Component Editor 15.0
# Fri Aug 26 17:59:33 CST 2016
# DO NOT MODIFY


# 
# vga_composer "VGA Composer" v1.1
#  2016.08.26.17:59:33
# 
# 

# 
# request TCL package from ACDS 15.0
# 
package require -exact qsys 15.0


# 
# module vga_composer
# 
set_module_property DESCRIPTION ""
set_module_property NAME vga_composer
set_module_property VERSION 1.1
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "VGA Composer"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL vga_composer
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file NEEE.vhd VHDL PATH src/NEEE.vhd
add_fileset_file ip_fifo.vhd VHDL PATH src/ip_fifo.vhd
add_fileset_file vga_controller.vhd VHDL PATH src/vga_controller.vhd
add_fileset_file mm_read_buffer_addr.vhd VHDL PATH src/mm_read_buffer_addr.vhd
add_fileset_file vga_composer.vhd VHDL PATH src/vga_composer.vhd TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL vga_composer
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file NEEE.vhd VHDL PATH src/NEEE.vhd
add_fileset_file ip_fifo.vhd VHDL PATH src/ip_fifo.vhd
add_fileset_file vga_controller.vhd VHDL PATH src/vga_controller.vhd
add_fileset_file mm_read_buffer_addr.vhd VHDL PATH src/mm_read_buffer_addr.vhd
add_fileset_file vga_composer.vhd VHDL PATH src/vga_composer.vhd

add_fileset SIM_VHDL SIM_VHDL "" ""
set_fileset_property SIM_VHDL TOP_LEVEL vga_composer
set_fileset_property SIM_VHDL ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VHDL ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file NEEE.vhd VHDL PATH src/NEEE.vhd
add_fileset_file ip_fifo.vhd VHDL PATH src/ip_fifo.vhd
add_fileset_file vga_controller.vhd VHDL PATH src/vga_controller.vhd
add_fileset_file mm_read_buffer_addr.vhd VHDL PATH src/mm_read_buffer_addr.vhd
add_fileset_file vga_composer.vhd VHDL PATH src/vga_composer.vhd


# 
# parameters
# 
add_parameter DATA_WIDTH POSITIVE 32
set_parameter_property DATA_WIDTH DEFAULT_VALUE 32
set_parameter_property DATA_WIDTH DISPLAY_NAME DATA_WIDTH
set_parameter_property DATA_WIDTH TYPE POSITIVE
set_parameter_property DATA_WIDTH UNITS None
set_parameter_property DATA_WIDTH ALLOWED_RANGES 1:2147483647
set_parameter_property DATA_WIDTH HDL_PARAMETER true
add_parameter FIFO_LENGTH_LOG_2 POSITIVE 6
set_parameter_property FIFO_LENGTH_LOG_2 DEFAULT_VALUE 6
set_parameter_property FIFO_LENGTH_LOG_2 DISPLAY_NAME FIFO_LENGTH_LOG_2
set_parameter_property FIFO_LENGTH_LOG_2 TYPE POSITIVE
set_parameter_property FIFO_LENGTH_LOG_2 UNITS None
set_parameter_property FIFO_LENGTH_LOG_2 ALLOWED_RANGES 1:2147483647
set_parameter_property FIFO_LENGTH_LOG_2 HDL_PARAMETER true
add_parameter ADDR_WIDTH POSITIVE 27
set_parameter_property ADDR_WIDTH DEFAULT_VALUE 27
set_parameter_property ADDR_WIDTH DISPLAY_NAME ADDR_WIDTH
set_parameter_property ADDR_WIDTH TYPE POSITIVE
set_parameter_property ADDR_WIDTH UNITS None
set_parameter_property ADDR_WIDTH ALLOWED_RANGES 1:2147483647
set_parameter_property ADDR_WIDTH HDL_PARAMETER true
add_parameter CAM_BANK STD_LOGIC_VECTOR 0
set_parameter_property CAM_BANK DEFAULT_VALUE 0
set_parameter_property CAM_BANK DISPLAY_NAME CAM_BANK
set_parameter_property CAM_BANK TYPE STD_LOGIC_VECTOR
set_parameter_property CAM_BANK UNITS None
set_parameter_property CAM_BANK ALLOWED_RANGES 0:3
set_parameter_property CAM_BANK HDL_PARAMETER true
add_parameter RENDER_BANK STD_LOGIC_VECTOR 1
set_parameter_property RENDER_BANK DEFAULT_VALUE 1
set_parameter_property RENDER_BANK DISPLAY_NAME RENDER_BANK
set_parameter_property RENDER_BANK TYPE STD_LOGIC_VECTOR
set_parameter_property RENDER_BANK UNITS None
set_parameter_property RENDER_BANK ALLOWED_RANGES 0:3
set_parameter_property RENDER_BANK HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point conduit
# 
add_interface conduit conduit end
set_interface_property conduit associatedClock clock
set_interface_property conduit associatedReset ""
set_interface_property conduit ENABLED true
set_interface_property conduit EXPORT_OF ""
set_interface_property conduit PORT_NAME_MAP ""
set_interface_property conduit CMSIS_SVD_VARIABLES ""
set_interface_property conduit SVD_ADDRESS_GROUP ""

add_interface_port conduit VGA_B vga_b Output 8
add_interface_port conduit VGA_BLANK_N vga_blank_n Output 1
add_interface_port conduit VGA_CLK vga_clk Output 1
add_interface_port conduit VGA_G vga_g Output 8
add_interface_port conduit VGA_HS vga_hs Output 1
add_interface_port conduit VGA_R vga_r Output 8
add_interface_port conduit VGA_SYNC_N vga_sync_n Output 1
add_interface_port conduit VGA_VS vga_vs Output 1
add_interface_port conduit clk_vga clk_vga Input 1


# 
# connection point avalon_master_cam
# 
add_interface avalon_master_cam avalon start
set_interface_property avalon_master_cam addressUnits SYMBOLS
set_interface_property avalon_master_cam associatedClock clock
set_interface_property avalon_master_cam associatedReset reset
set_interface_property avalon_master_cam bitsPerSymbol 8
set_interface_property avalon_master_cam burstOnBurstBoundariesOnly false
set_interface_property avalon_master_cam burstcountUnits WORDS
set_interface_property avalon_master_cam doStreamReads false
set_interface_property avalon_master_cam doStreamWrites false
set_interface_property avalon_master_cam holdTime 0
set_interface_property avalon_master_cam linewrapBursts false
set_interface_property avalon_master_cam maximumPendingReadTransactions 0
set_interface_property avalon_master_cam maximumPendingWriteTransactions 0
set_interface_property avalon_master_cam readLatency 0
set_interface_property avalon_master_cam readWaitTime 1
set_interface_property avalon_master_cam setupTime 0
set_interface_property avalon_master_cam timingUnits Cycles
set_interface_property avalon_master_cam writeWaitTime 0
set_interface_property avalon_master_cam ENABLED true
set_interface_property avalon_master_cam EXPORT_OF ""
set_interface_property avalon_master_cam PORT_NAME_MAP ""
set_interface_property avalon_master_cam CMSIS_SVD_VARIABLES ""
set_interface_property avalon_master_cam SVD_ADDRESS_GROUP ""

add_interface_port avalon_master_cam cam_address address Output addr_width
add_interface_port avalon_master_cam cam_read read Output 1
add_interface_port avalon_master_cam cam_readdata readdata Input data_width
add_interface_port avalon_master_cam cam_waitrequest waitrequest Input 1
add_interface_port avalon_master_cam cam_readdatavalid readdatavalid Input 1
add_interface_port avalon_master_cam cam_lock lock Output 1


# 
# connection point avalon_master_render
# 
add_interface avalon_master_render avalon start
set_interface_property avalon_master_render addressUnits SYMBOLS
set_interface_property avalon_master_render associatedClock clock
set_interface_property avalon_master_render associatedReset reset
set_interface_property avalon_master_render bitsPerSymbol 8
set_interface_property avalon_master_render burstOnBurstBoundariesOnly false
set_interface_property avalon_master_render burstcountUnits WORDS
set_interface_property avalon_master_render doStreamReads false
set_interface_property avalon_master_render doStreamWrites false
set_interface_property avalon_master_render holdTime 0
set_interface_property avalon_master_render linewrapBursts false
set_interface_property avalon_master_render maximumPendingReadTransactions 0
set_interface_property avalon_master_render maximumPendingWriteTransactions 0
set_interface_property avalon_master_render readLatency 0
set_interface_property avalon_master_render readWaitTime 1
set_interface_property avalon_master_render setupTime 0
set_interface_property avalon_master_render timingUnits Cycles
set_interface_property avalon_master_render writeWaitTime 0
set_interface_property avalon_master_render ENABLED true
set_interface_property avalon_master_render EXPORT_OF ""
set_interface_property avalon_master_render PORT_NAME_MAP ""
set_interface_property avalon_master_render CMSIS_SVD_VARIABLES ""
set_interface_property avalon_master_render SVD_ADDRESS_GROUP ""

add_interface_port avalon_master_render render_address address Output addr_width
add_interface_port avalon_master_render render_read read Output 1
add_interface_port avalon_master_render render_readdata readdata Input data_width
add_interface_port avalon_master_render render_waitrequest waitrequest Input 1
add_interface_port avalon_master_render render_readdatavalid readdatavalid Input 1
add_interface_port avalon_master_render render_lock lock Output 1


# 
# connection point cam_buffer
# 
add_interface cam_buffer conduit end
set_interface_property cam_buffer associatedClock clock
set_interface_property cam_buffer associatedReset ""
set_interface_property cam_buffer ENABLED true
set_interface_property cam_buffer EXPORT_OF ""
set_interface_property cam_buffer PORT_NAME_MAP ""
set_interface_property cam_buffer CMSIS_SVD_VARIABLES ""
set_interface_property cam_buffer SVD_ADDRESS_GROUP ""

add_interface_port cam_buffer cam_buffer_port buffer_port Input 2
add_interface_port cam_buffer cam_vsync_out buffer_vsync Output 1


# 
# connection point render_buffer
# 
add_interface render_buffer conduit end
set_interface_property render_buffer associatedClock clock
set_interface_property render_buffer associatedReset ""
set_interface_property render_buffer ENABLED true
set_interface_property render_buffer EXPORT_OF ""
set_interface_property render_buffer PORT_NAME_MAP ""
set_interface_property render_buffer CMSIS_SVD_VARIABLES ""
set_interface_property render_buffer SVD_ADDRESS_GROUP ""

add_interface_port render_buffer render_buffer_port buffer_port Input 2
add_interface_port render_buffer render_vsync_out buffer_vsync Output 1

