# TCL File Generated by Component Editor 15.0
# Sat Aug 27 20:54:08 CST 2016
# DO NOT MODIFY


# 
# vga_st_composer "VGA Composer (ST)" v1.0
#  2016.08.27.20:54:08
# 
# 

# 
# request TCL package from ACDS 15.0
# 
package require -exact qsys 15.0


# 
# module vga_st_composer
# 
set_module_property DESCRIPTION ""
set_module_property NAME vga_st_composer_overlay
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "VGA Composer with Overlay (ST)"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL vga_composer
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file vga_controller.vhd VHDL PATH src/vga_controller.vhd
add_fileset_file vga_st_composer_overlay.vhd VHDL PATH src/vga_st/vga_st_composer_overlay.vhd TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL vga_composer
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file vga_controller.vhd VHDL PATH src/vga_controller.vhd
add_fileset_file vga_st_composer_overlay.vhd VHDL PATH src/vga_st/vga_st_composer_overlay.vhd

add_fileset SIM_VHDL SIM_VHDL "" ""
set_fileset_property SIM_VHDL TOP_LEVEL vga_composer
set_fileset_property SIM_VHDL ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VHDL ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file vga_controller.vhd VHDL PATH src/vga_controller.vhd
add_fileset_file vga_st_composer_overlay.vhd VHDL PATH src/vga_st/vga_st_composer_overlay.vhd


# 
# parameters
# 
add_parameter DATA_WIDTH POSITIVE 32
set_parameter_property DATA_WIDTH DEFAULT_VALUE 32
set_parameter_property DATA_WIDTH DISPLAY_NAME DATA_WIDTH
set_parameter_property DATA_WIDTH TYPE POSITIVE
set_parameter_property DATA_WIDTH UNITS None
set_parameter_property DATA_WIDTH ALLOWED_RANGES 1:2147483647
set_parameter_property DATA_WIDTH HDL_PARAMETER true
add_parameter FIFO_LENGTH_LOG_2 POSITIVE 6
set_parameter_property FIFO_LENGTH_LOG_2 DEFAULT_VALUE 6
set_parameter_property FIFO_LENGTH_LOG_2 DISPLAY_NAME FIFO_LENGTH_LOG_2
set_parameter_property FIFO_LENGTH_LOG_2 TYPE POSITIVE
set_parameter_property FIFO_LENGTH_LOG_2 UNITS None
set_parameter_property FIFO_LENGTH_LOG_2 ALLOWED_RANGES 1:2147483647
set_parameter_property FIFO_LENGTH_LOG_2 HDL_PARAMETER true


# 
# display items
# 


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock ""
set_interface_property reset synchronousEdges NONE
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point Conduit
# 
add_interface Conduit conduit end
set_interface_property Conduit associatedClock ""
set_interface_property Conduit associatedReset ""
set_interface_property Conduit ENABLED true
set_interface_property Conduit EXPORT_OF ""
set_interface_property Conduit PORT_NAME_MAP ""
set_interface_property Conduit CMSIS_SVD_VARIABLES ""
set_interface_property Conduit SVD_ADDRESS_GROUP ""

add_interface_port Conduit VGA_B vga_b Output 8
add_interface_port Conduit VGA_BLANK_N vga_blank_n Output 1
add_interface_port Conduit VGA_CLK vga_clk Output 1
add_interface_port Conduit VGA_G vga_g Output 8
add_interface_port Conduit VGA_HS vga_hs Output 1
add_interface_port Conduit VGA_R vga_r Output 8
add_interface_port Conduit VGA_SYNC_N vga_sync_n Output 1
add_interface_port Conduit VGA_VS vga_vs Output 1


# 
# connection point sink_camera
# 
add_interface sink_camera avalon_streaming end
set_interface_property sink_camera associatedClock clk_vga
set_interface_property sink_camera associatedReset reset
set_interface_property sink_camera dataBitsPerSymbol 8
set_interface_property sink_camera errorDescriptor ""
set_interface_property sink_camera firstSymbolInHighOrderBits true
set_interface_property sink_camera maxChannel 0
set_interface_property sink_camera readyLatency 0
set_interface_property sink_camera ENABLED true
set_interface_property sink_camera EXPORT_OF ""
set_interface_property sink_camera PORT_NAME_MAP ""
set_interface_property sink_camera CMSIS_SVD_VARIABLES ""
set_interface_property sink_camera SVD_ADDRESS_GROUP ""

add_interface_port sink_camera cam_data data Input data_width
add_interface_port sink_camera cam_ready ready Output 1


# 
# connection point sink_render
# 
add_interface sink_render avalon_streaming end
set_interface_property sink_render associatedClock clk_vga
set_interface_property sink_render associatedReset reset
set_interface_property sink_render dataBitsPerSymbol 8
set_interface_property sink_render errorDescriptor ""
set_interface_property sink_render firstSymbolInHighOrderBits true
set_interface_property sink_render maxChannel 0
set_interface_property sink_render readyLatency 0
set_interface_property sink_render ENABLED true
set_interface_property sink_render EXPORT_OF ""
set_interface_property sink_render PORT_NAME_MAP ""
set_interface_property sink_render CMSIS_SVD_VARIABLES ""
set_interface_property sink_render SVD_ADDRESS_GROUP ""

add_interface_port sink_render render_data data Input data_width
add_interface_port sink_render render_ready ready Output 1


# 
# connection point sink_overlay
# 
add_interface sink_overlay avalon_streaming end
set_interface_property sink_overlay associatedClock clk_vga
set_interface_property sink_overlay associatedReset reset
set_interface_property sink_overlay dataBitsPerSymbol 8
set_interface_property sink_overlay errorDescriptor ""
set_interface_property sink_overlay firstSymbolInHighOrderBits true
set_interface_property sink_overlay maxChannel 0
set_interface_property sink_overlay readyLatency 0
set_interface_property sink_overlay ENABLED true
set_interface_property sink_overlay EXPORT_OF ""
set_interface_property sink_overlay PORT_NAME_MAP ""
set_interface_property sink_overlay CMSIS_SVD_VARIABLES ""
set_interface_property sink_overlay SVD_ADDRESS_GROUP ""

add_interface_port sink_overlay overlay_data data Input data_width
add_interface_port sink_overlay overlay_ready ready Output 1


# 
# connection point clk_vga
# 
add_interface clk_vga clock end
set_interface_property clk_vga clockRate 0
set_interface_property clk_vga ENABLED true
set_interface_property clk_vga EXPORT_OF ""
set_interface_property clk_vga PORT_NAME_MAP ""
set_interface_property clk_vga CMSIS_SVD_VARIABLES ""
set_interface_property clk_vga SVD_ADDRESS_GROUP ""

add_interface_port clk_vga clk_vga clk Input 1

