//=======================================================
//	This code is generated by Terasic System Builder
//=======================================================

module anxious_capture_top

`include "./common.v"

`include "./camera_gpio_defs.v"

assign FAN_CTRL = SW[0]; // turn off FAN

wire clk_camera;
wire clk_qsys;
wire clk_vga;

cam_pll U_cam_pll (
	.inclk0 (CLOCK_50),
	.c0     (clk_camera),
	.c1     (clk_qsys),
	.c2     (DRAM_CLK),
	.c3     (clk_vga)
);

wire [1:0] overlay_buffer_port;
wire overlay_buffer_vsync;

wire [1:0] recog_buffer_port_0, recog_buffer_port_1;
wire recog_buffer_vsync_0, recog_buffer_vsync_1;

`define RENDER_CORES 1
wire [1:0] render_buffer_port;
wire [`RENDER_CORES-1:0] render_vsync;
reg render_vsync_all, render_vsync_any;
assign render_vsync_all = render_vsync[0]; // and
assign render_vsync_any = render_vsync[0]; // or
reg render_start, render_start_r, render_start_rin;

always @ (posedge clk_qsys) begin
	render_start_r <= render_start_rin;
end

always begin
	render_start = render_start_r;
	if (render_vsync_all == 1'b1) begin
		render_start = 1'b1;
	end else if (render_vsync_any == 1'b0) begin
		render_start = 1'b0;
	end
	render_start_rin <= render_start;
end

wire render_buffer_vsync;
assign render_buffer_vsync = render_vsync_all;

assign SSRAM_CLK = DRAM_CLK;

anxious_capture u0 (
    .cam_buffer_switcher_enable_enable                  (SW[4]),

    .camera_mm_0_camera_wires_cam_din                   (`CAM_DIN_0),
    .camera_mm_0_camera_wires_cam_href                  (`CAM_HREF_0),
    .camera_mm_0_camera_wires_cam_pclk                  (`CAM_PCLK_0),
    // .camera_mm_0_camera_wires_cam_pwdn                  (),
    // .camera_mm_0_camera_wires_cam_reset                 (),
    .camera_mm_0_camera_wires_cam_vsync                 (`CAM_VSYNC_0),
    // .camera_mm_0_camera_wires_cam_xclk                  (),
    .camera_mm_0_camera_wires_clk_camera                (clk_camera),
    .camera_mm_0_camera_wires_enable_n                  (SW[3]),

    .camera_sioc_0_external_connection_export           (`CAM_SIOC_0),
    .camera_sioc_1_external_connection_export           (`CAM_SIOC_1),
    .camera_siod_0_external_connection_export           (`CAM_SIOD_0),
    .camera_siod_1_external_connection_export           (`CAM_SIOD_1),

    .camera_st_0_conduit_cam_din                        (`CAM_DIN_0),
    .camera_st_0_conduit_cam_href                       (`CAM_HREF_0),
    .camera_st_0_conduit_cam_pclk                       (`CAM_PCLK_0),
    .camera_st_0_conduit_cam_pwdn                       (`CAM_PWDN_0),
    .camera_st_0_conduit_cam_reset                      (`CAM_RESET_0),
    .camera_st_0_conduit_cam_vsync                      (`CAM_VSYNC_0),
    .camera_st_0_conduit_cam_xclk                       (`CAM_XCLK_0),
    .camera_st_0_conduit_clk_camera                     (clk_camera),
    .camera_st_0_conduit_enable_n                       (SW[1]),

    .camera_st_1_conduit_cam_din                        (`CAM_DIN_1),
    .camera_st_1_conduit_cam_href                       (`CAM_HREF_1),
    .camera_st_1_conduit_cam_pclk                       (`CAM_PCLK_1),
    .camera_st_1_conduit_cam_pwdn                       (`CAM_PWDN_1),
    .camera_st_1_conduit_cam_reset                      (`CAM_RESET_1),
    .camera_st_1_conduit_cam_vsync                      (`CAM_VSYNC_1),
    .camera_st_1_conduit_cam_xclk                       (`CAM_XCLK_1),
    .camera_st_1_conduit_clk_camera                     (clk_camera),
    .camera_st_1_conduit_enable_n                       (SW[2]),

    .clk_clk                                            (clk_qsys),

    .ir_receiver_0_ir_clock_clk                         (CLOCK_50),
    .ir_receiver_0_irda_IRDA                            (IRDA_RXD),

    .key_pio_external_connection_export                 (KEY[1]),

    .new_sdram_controller_0_wire_addr                   (DRAM_ADDR),
    .new_sdram_controller_0_wire_ba                     (DRAM_BA),
    .new_sdram_controller_0_wire_cas_n                  (DRAM_CAS_N),
    .new_sdram_controller_0_wire_cke                    (DRAM_CKE),
    .new_sdram_controller_0_wire_cs_n                   (DRAM_CS_N),
    .new_sdram_controller_0_wire_dq                     (DRAM_DQ),
    .new_sdram_controller_0_wire_dqm                    (DRAM_DQM),
    .new_sdram_controller_0_wire_ras_n                  (DRAM_RAS_N),
    .new_sdram_controller_0_wire_we_n                   (DRAM_WE_N),

    .overlay_buffer_switcher_enable_enable              (SW[7]),
    .overlay_buffer_switcher_write_buffer_buffer_port   (overlay_buffer_port),
    .overlay_buffer_switcher_write_buffer_buffer_vsync  (overlay_buffer_vsync),
    .overlay_port_pio_external_connection_export        (overlay_buffer_port),
    .overlay_vsync_pio_external_connection_export       (overlay_buffer_vsync),

    .recog_buffer_port_pio_0_external_connection_export (recog_buffer_port_0),
    .recog_buffer_port_pio_1_external_connection_export (recog_buffer_port_1),
    .recog_buffer_switcher_0_enable_enable              (SW[5]),
    .recog_buffer_switcher_0_read_buffer_buffer_port    (recog_buffer_port_0),
    .recog_buffer_switcher_0_read_buffer_buffer_vsync   (recog_buffer_vsync_0),
    .recog_buffer_switcher_1_enable_enable              (SW[5]),
    .recog_buffer_switcher_1_read_buffer_buffer_port    (recog_buffer_port_1),
    .recog_buffer_switcher_1_read_buffer_buffer_vsync   (recog_buffer_vsync_1),
    .recog_vsync_pio_0_external_connection_export       (recog_buffer_vsync_0),
    .recog_vsync_pio_1_external_connection_export       (recog_buffer_vsync_1),

    .render_buffer_switcher_enable_enable               (SW[6]),
    .render_buffer_switcher_write_buffer_buffer_port    (render_buffer_port),
    .render_buffer_switcher_write_buffer_buffer_vsync   (render_buffer_vsync),
    .render_port_pio_external_connection_export         (render_buffer_port),
    .render_start_pio_external_connection_export        (render_start_r),
    .render_vsync_pio_0_external_connection_export      (render_vsync[0]),

    .reset_reset_n                                      (KEY[0]),

    .vga_st_composer_overlay_0_conduit_vga_b            (VGA_B),
    .vga_st_composer_overlay_0_conduit_vga_blank_n      (VGA_BLANK_N),
    .vga_st_composer_overlay_0_conduit_vga_clk          (VGA_CLK),
    .vga_st_composer_overlay_0_conduit_vga_g            (VGA_G),
    .vga_st_composer_overlay_0_conduit_vga_hs           (VGA_HS),
    .vga_st_composer_overlay_0_conduit_vga_r            (VGA_R),
    .vga_st_composer_overlay_0_conduit_vga_sync_n       (VGA_SYNC_N),
    .vga_st_composer_overlay_0_conduit_vga_vs           (VGA_VS),

    .clk_vga_clk                                        (clk_vga),
    .vid_read_buffer_0_vsync_s_vsync                    (VGA_VS),
    .render_mm_to_st_vga_vsync_s_vsync                  (VGA_VS),
    .cam_mm_to_st_vga_vsync_s_vsync                     (VGA_VS),

	.fs_wires_sram_we_n                                 (SSRAM_WE_N),
	.fs_wires_fl_we_n                                   (FL_WE_N),
	.fs_wires_sram_oe_n                                 (SSRAM_OE_N),
	.fs_wires_sram_begintransfer_n                      (SSRAM_ADSC_N),
	.fs_wires_fl_oe_n                                   (FL_OE_N),
	.fs_wires_sram_ce_n                                 (),
	.fs_wires_fl_ce_n                                   (FL_CE_N),
	.fs_wires_sram_be_n                                 (SSRAM_BE),
	.fs_wires_fs_data                                   (FS_DQ),
	.fs_wires_sram_reset_n                              (),
	.fs_wires_fs_addr                                   (FS_ADDR)
);

endmodule
