
//=======================================================
//	This code is generated by Terasic System Builder
//=======================================================

module anxious_up_top(

	//////////// CLOCK //////////
	CLOCK_50,	// BANK 4
	CLOCK2_50,	// BANK 7
	CLOCK3_50,	// BANK 3A

	//////////// LED (High Active) //////////
	LEDG,
	LEDR,

	//////////// KEY (Active Low) //////////
	KEY,

	//////////// SW //////////
	SW,

	//////////// SEG7 (Low Active) //////////
	HEX0,
	HEX1,
	HEX2,
	HEX3,
	HEX4,
	HEX5,
	HEX6,
	HEX7,

	//////////// LCD //////////
	LCD_DATA,
	LCD_EN,
	LCD_ON,
	LCD_RS,
	LCD_RW,

	//////////// SDCARD //////////
	SD_CLK,
	SD_CMD,
	SD_DAT,
	SD_WP_N,

	//////////// VGA //////////
	VGA_B,
	VGA_BLANK_N,
	VGA_CLK,
	VGA_G,
	VGA_HS,
	VGA_R,
	VGA_SYNC_N,
	VGA_VS,

	//////////// IR Receiver //////////
	IRDA_RXD,

	//////////// SDRAM //////////
	DRAM_ADDR,
	DRAM_BA,
	DRAM_CAS_N,
	DRAM_CKE,
	DRAM_CLK,
	DRAM_CS_N,
	DRAM_DQ,
	DRAM_DQM,
	DRAM_RAS_N,
	DRAM_WE_N,

	//////////// GPIO, GPIO connect to GPIO Default //////////
	GPIO,

	//////////// Fan Control //////////
	FAN_CTRL
);

//=======================================================
//	PARAMETER declarations
//=======================================================


//=======================================================
//	PORT declarations
//=======================================================

//////////// CLOCK //////////
input						CLOCK_50;
input						CLOCK2_50;
input						CLOCK3_50;

//////////// LED (High Active) //////////
output			 [8:0]		LEDG;
output			[17:0]		LEDR;

//////////// KEY (Active Low) //////////
input			 [3:0]		KEY;

//////////// SW //////////
input			[17:0]		SW;

//////////// SEG7 (Low Active) //////////
output			 [6:0]		HEX0;
output			 [6:0]		HEX1;
output			 [6:0]		HEX2;
output			 [6:0]		HEX3;
output			 [6:0]		HEX4;
output			 [6:0]		HEX5;
output			 [6:0]		HEX6;
output			 [6:0]		HEX7;

//////////// LCD //////////
inout			 [7:0]		LCD_DATA;
output						LCD_EN;
output						LCD_ON;
output						LCD_RS;
output						LCD_RW;

//////////// SDCARD //////////
output						SD_CLK;
inout						SD_CMD;
inout			 [3:0]		SD_DAT;
input						SD_WP_N;

//////////// VGA //////////
output			 [7:0]		VGA_B;
output						VGA_BLANK_N;
output						VGA_CLK;
output			 [7:0]		VGA_G;
output						VGA_HS;
output			 [7:0]		VGA_R;
output						VGA_SYNC_N;
output						VGA_VS;

//////////// IR Receiver //////////
input						IRDA_RXD;

//////////// SDRAM //////////
output			[12:0]		DRAM_ADDR;
output			 [1:0]		DRAM_BA;
output						DRAM_CAS_N;
output						DRAM_CKE;
output						DRAM_CLK;
output						DRAM_CS_N;
inout			[31:0]		DRAM_DQ;
output			 [3:0]		DRAM_DQM;
output						DRAM_RAS_N;
output						DRAM_WE_N;

//////////// GPIO, GPIO connect to GPIO Default //////////
inout			[0:35]		GPIO;

//////////// Fan Control //////////
inout						FAN_CTRL;


//=======================================================
//	REG/WIRE declarations
//=======================================================




//=======================================================
//	Structural coding
//=======================================================



//////////// FAN Control //////////
assign FAN_CTRL = SW[0];

wire clk_camera, clk_qsts, clk_sdram, clk_vga;

cam_pll U_cam_pll (
	.inclk0 (CLOCK_50),
	.c0     (clk_camera),
	.c1     (clk_qsys),
	.c2     (clk_sdram),
	.c3     (clk_vga)
);


assign DRAM_CLK = clk_sdram;

anxious_up U_sys (
    .clk_qsys_clk                      (clk_qsys),    //                         clk.clk
    .reset_qsys_reset_n                (KEY[0]),      //                       reset.reset_n

	.camera_up_0_conduit_clk_camera    (clk_camera),  //         camera_up_0_conduit.clk_camera
	.camera_up_0_conduit_enable_n      (SW[1]),       //                            .enable_n
	.camera_up_0_conduit_cam_din       (GPIO[26:33]), //                            .cam_din
	.camera_up_0_conduit_cam_href      (GPIO[23]),    //                            .cam_href
	.camera_up_0_conduit_cam_pclk      (GPIO[24]),    //                            .cam_pclk
	.camera_up_0_conduit_cam_pwdn      (GPIO[35]),    //                            .cam_pwdn
	.camera_up_0_conduit_cam_reset     (GPIO[34]),    //                            .cam_reset
	.camera_up_0_conduit_cam_vsync     (GPIO[22]),    //                            .cam_vsync
	.camera_up_0_conduit_cam_xclk      (GPIO[25]),    //                            .cam_xclk
	
	.new_sdram_controller_0_wire_addr  (DRAM_ADDR),   // new_sdram_controller_0_wire.addr
	.new_sdram_controller_0_wire_ba    (DRAM_BA),     //                            .ba
	.new_sdram_controller_0_wire_cas_n (DRAM_CAS_N),  //                            .cas_n
	.new_sdram_controller_0_wire_cke   (DRAM_CKE),    //                            .cke
	.new_sdram_controller_0_wire_cs_n  (DRAM_CS_N),   //                            .cs_n
	.new_sdram_controller_0_wire_dq    (DRAM_DQ),     //                            .dq
	.new_sdram_controller_0_wire_dqm   (DRAM_DQM),    //                            .dqm
	.new_sdram_controller_0_wire_ras_n (DRAM_RAS_N),  //                            .ras_n
	.new_sdram_controller_0_wire_we_n  (DRAM_WE_N),   //                            .we_n
//	.sys_sdram_pll_0_sdram_clk_clk     (DRAM_CLK),    //   sys_sdram_pll_0_sdram_clk.clk
	
	.vga_mm_0_conduit_vga_b            (VGA_B),       //            vga_mm_0_conduit.vga_b
	.vga_mm_0_conduit_vga_blank_n      (VGA_BLANK_N), //                            .vga_blank_n
	.vga_mm_0_conduit_vga_clk          (VGA_CLK),     //                            .vga_clk
	.vga_mm_0_conduit_vga_g            (VGA_G),       //                            .vga_g
	.vga_mm_0_conduit_vga_hs           (VGA_HS),      //                            .vga_hs
	.vga_mm_0_conduit_vga_r            (VGA_R),       //                            .vga_r
	.vga_mm_0_conduit_vga_sync_n       (VGA_SYNC_N),  //                            .vga_sync_n
	.vga_mm_0_conduit_vga_vs           (VGA_VS),      //                            .vga_vs
	.vga_mm_0_conduit_clk_vga          (clk_vga),     //                            .clk_vga
	.vga_mm_0_buffer_port_address      (SW[3:2]),
//	.video_vga_controller_0_external_interface_CLK   (VGA_CLK),      // video_vga_controller_0_external_interface.CLK
//    .video_vga_controller_0_external_interface_HS    (VGA_HS),       //                                          .HS
//    .video_vga_controller_0_external_interface_VS    (VGA_VS),       //                                          .VS
////    .video_vga_controller_0_external_interface_BLANK (VGA_BLANK_N),  //                                          .BLANK
////    .video_vga_controller_0_external_interface_SYNC  (SYNC),  //                                          .SYNC
//    .video_vga_controller_0_external_interface_R     (VGA_R),        //                                          .R
//    .video_vga_controller_0_external_interface_G     (VGA_G),        //                                          .G
//    .video_vga_controller_0_external_interface_B     (VGA_B)         //                                          .B
);

endmodule
